version: '3.8'

services:
  mysql-confectionery-webstore:
    container_name: 'mysql-confectionery-webstore'
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=confectionery_webstore
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

