export enum OrderStatus {
  OPEN = 'OPEN',
  PAID = 'PAID',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  RETURNING = 'RETURNING',
  FINISHED = 'FINISHED',
}

export const OrderStatusTransitions = {
  OPEN: ['PAID'],
  PAID: ['DELIVERING'],
  DELIVERING: ['DELIVERED'],
  DELIVERED: ['RETURNING', 'FINISHED'],
  RETURNING: ['FINISHED'],
};
